### ISSUE TITLE
Build intermediate layer to communicate with different databases

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-core#103]
- [x] Review codebase where TheGraph service is used (myxo, core, api)
- [x] Implement abstraction layer in the core (only with the existing graph queries)
- [x] Run core tests (we should check if it matters that the api is importing the old core lib)
- [x] Build unit test
- [x] Test in stg
- [x] Build
- [x] Document

**Comment by JacqueGM** [comment]
@mikozet  fixing test  for the intermediate layer just with the graph
