### ISSUE TITLE
Investigate behaviour of getNetwork and mutually trusted

### ISSUE THREAD

**Issue by louilinn** [CirclesUBI/circles-core#224]
https://github.com/CirclesUBI/circles-core/blob/5286799903e3c42bd3eddaae6e09847a2097e999/src/trust.js#L86 

Mutually trusted tab in app profiles is confusing and should be revised. 

Investigate the conditions for current filtering and make a suggestion for updating

**Comment by louilinn** [comment]
What behaviour is currently and what is desired.
You can consider the 9 possible trust relations between 3 accounts.

| A- B | B - C | B is mutually trusted |
|---|---|---|
| x | x | no |
| x | > | no |
| x | > | no |
| > | x | no |
| > | x | no |
| > | > | ? |
| > | < | yes?? |
| < | < | ? |
| < | > | ? |

**Comment by louilinn** [comment]
Find: SW (cannot receive but only give trust) always have no mutually trusted in their profile. Suggesting that behaviour might look for scenario x

**Comment by JacqueGM** [comment]
We need to take into consideration that shared wallets cannot trust each other

**Comment by louilinn** [comment]
Documentation of findings 

#### Current behaviour:
mutuallyTrusted includes the intersection of those that trust the signed in wallet and those that trust the visited profile. (line 4 and also line 6,7,9)
This information is not useful. This was likely a mistake by the first devs as they confused the directions of trusts.

#### Desired behaviour:
mutuallyTrusted includes the intersection of those that are trusted by the signed in wallet and those that are trusted by the visited profile. (line 2 and also line 3,8,9)

| Trust |  A ? B | B ? C | B is mutually trusted currently? | mutually trusted desired |
|---|---|---|---|---|
| 1 | > | > | no | no |
| 2 | > | < | no | yes |
| 3 | > | = | no | yes |
| 4 | < | > | yes | no |
| 5 | < | < | no | yes |
| 6 | < | = | yes | no |
| 7 | = | > | yes | no |
| 8 | = | < | no | yes |
| 9 | = | = | yes | yes |

> trusts
< trusted by
= mutual trust

#### Justification
It is useful for users to know what users (tokens) they both trust.
If the signed in wallet trusts a user is means they potentially hold such tokens. If the dont trust them, they don't hold them (unless they have previously trusted them, received tokens and then untrusted them).
If a wallet profile you visit trusts a user/token, they will accept that token meaning it can be sent directly to them without transitive transfers.
If you both trust many of the same tokens, you are likely to easily be able to send many circles to each other. 

It is not so useful to know that you are trusted by the same person because it does not enable sending circles.
It could be useful to know that you have a A > B > C trust connection because that will tell you C is likely to be able to transfer to A transitively. But this kind of information involves much more complexity and is more tricky to express linguistically in a simple way to the user.

"Mutually trusted" is a straight forward concept. We both trust these people meaning we both potentially hold and accept these circles.

#### Further context and continued improvement
Mutually trusted count also appears in "Trust search" to help guide users to identify users in their network / with shared connections.
Mutually trusted count in search and mutually trusted accounts in profile only appears if the user is either trusted by you or is trusting you. This is because it would be too complex to calculate the overlap of ALL circles users, so we are fetching the closest ones.
An undesired effect is that mutually trusted connections never appear between two shared wallets because they are not sharing any trust as they cannot be trusted by each other.

We are adding another issue to fetch mutually trusted in profile view for all accounts.
At least now we have the fixed the behaviour to be as intended and it will be released soon. Then we will extend the behaviour to more profiles.
