### ISSUE TITLE
Show and filter activities only related to another user address

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-core#53]

**Comment by louilinn** [comment]
Required for https://github.com/CirclesUBI/circles-myxogastria/issues/102

**Comment by JacqueGM** [comment]
@JacqueGM  and @llunaCreixent  will help with this  @mikozet   :)

**Comment by JacqueGM** [comment]
Included in release https://github.com/CirclesUBI/circles-core/releases/tag/v4.6.0
