### ISSUE TITLE
Fix state issues with concurrently running tests

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/circles-core#68]
The token tests are failing with invalid nonce errors in the relayer service.

It seems that the same safe is used for multiple transactions at the same time which might cause the invalid transactions due to race conditions.

One solution could be to decouple the test state by creating a larger test network before all tests, with independent sub networks for each test.

**Comment by llunaCreixent** [comment]
Sometimes (only sometimes) the Token test fails with this msg (the Safe address changes though):

> Tried too many times waiting for condition "Wait until Safe 0xf489fB7639381aF4429Dd8Fd0F6Db4B3e2A4d7D4 got deployed"

**Comment by llunaCreixent** [comment]
It fails in the `deploySafe` function in `circles-core/test/helpers/transactions.js`:
```
  await loop(`Wait until Safe ${safeAddress} got deployed`, () =>
    web3.eth.getCode(safeAddress),
  );
```
We have to troubleshoot this.

**Comment by llunaCreixent** [comment]
See commit [c827f75](https://github.com/CirclesUBI/circles-core/pull/63/commits/c827f751ecca0a2511e638c4f927d5e413a09c24) in [fix-token-tests branch](https://github.com/CirclesUBI/circles-core/commits/fix-token-tests).

**Comment by adzialocha** [comment]
Related: https://github.com/CirclesUBI/safe-relay-service/issues/42
